version: "3.9"

volumes:
  postgres_data:
    driver: local
  pgadmin:
    driver: local

services:
  postgres:
    restart: on-failure
    container_name: postgres
    image: postgres:15.3
#    image: "postgres:13.2"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./db-data:/var/lib/postgresql/data/
#      - ./sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./database.local.env
    ports:
      - "5432:5432"
    networks:
      - keycloak
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.3
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    env_file:
      - ./database.local.env
    ports:
      - "5050:80"
    networks:
      - keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1
#    image: jboss/keycloak:16.1.1
    env_file:
      - ./keycloak.local.env
    command: start-dev
#      - start (required in production mode- but you need certificates here)
    ports:
      - "8180:8080"
#      - "8787:8787" # debug port
    depends_on:
      - postgres
    networks:
      - keycloak

networks:
  keycloak:
    name: keycloak
    driver: bridge